[phases.setup]
nixPkgs = ["...", "nodejs_20", "sqlite"]

[phases.build]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install",
  "cd frontend && npm run build",
  "cp -r frontend/build backend/frontend-build"
]

[start]
cmd = "cd backend && npm start"